### PR TITLE
Showing lists of "guests" for each event

### PR DESCRIPTION
**Pull request by lukeegan**

### CODE REVIEW

**Comment by gavincorkery** [comment]
The seeding works, but the list of event guests don't seem to populate properly. Also clicking the filter button on only list seems to cause all of the lists on that page to filter

**Comment by lukeegan** [comment]
UPDATE

**Comment by gavincorkery** [comment]
Looks good, the filtering bug mentioned above is still happening though. Do you plan to fix that in this PR?

**Comment by lukeegan** [comment]
Do you mean the sorting? I can't figure out why it's not working yet. Help appreciated with this bug

**Comment by gavincorkery** [comment]
Yeah the sorting. I'll have a look in a bit

**Pull request merged**
